"""Generated by tools/mascot/export_terminal.py -- do not edit by hand.

Nergal, the chaos-bringer mascot. Demon sprite by Stephen "Redshrike"
Challener (with Blarumyrran and LordNeo), from "6 More RPG Enemies" on
OpenGameArt.org, CC-BY 3.0 / OGA-BY 3.0; recolored, re-posed and composited
with an original cauldron for chaos-bringer. See CREDITS.md.
"""

FRAMES = 8
FRAME_MS = 140
TRANSPARENT = 0

FULL_WIDTH = 102
FULL_HEIGHT = 92
SMALL_WIDTH = 51
SMALL_HEIGHT = 46

PALETTE = (
    "#ff00ff", "#ff2e5b", "#ffd166", "#39ff88", "#c4ffd6", "#c4ffd6", "#d6e886", "#90b4b5",
    "#8fc23a", "#39ff88", "#7ecd49", "#8cc43c", "#62a446", "#30e97a", "#2ee377", "#2bde74",
    "#28d56e", "#25cc69", "#20bf61", "#1db45b", "#18a954", "#88999c", "#5a8b2d", "#5a8a2c",
    "#589031", "#717171", "#50973a", "#18954b", "#3d7932", "#157a3d", "#356c2a", "#356323",
    "#1c6a33", "#545f68", "#355e20", "#355c1f", "#3c474d", "#3a424a", "#373f46", "#1f5d2e",
    "#1b5529", "#2b4c1f", "#214c20", "#22431a", "#14421f", "#343b42", "#323940", "#30373e",
    "#2e343b", "#2c3239", "#2b3037", "#203b41", "#1d3c18", "#213b14", "#213a14", "#123419",
    "#342e36", "#272c32", "#252a2f", "#23282d", "#21262b", "#202429", "#1f2328", "#1f1f1f",
    "#1c2d15", "#1e2227", "#1e2226", "#1d2126", "#1c1f24", "#1a1e22", "#191d21", "#171b1f",
    "#161719", "#0f2613", "#0e1d0e", "#101a18", "#0d1a0b", "#14161a", "#111517", "#111317",
    "#101216", "#101215", "#101214", "#0f1113", "#0d0f11", "#0d0d0d", "#0e0603", "#0c1111",
    "#0b0c0f", "#0c0702", "#070707", "#0a0603", "#050301", "#020303", "#050201", "#050101",
)

FULL_DATA = (
    "eNrtnY1XGkcXh2nZgx5ikxipCC6GSg2IxCRyhJOPllhjUi3J+2pfSFgX9///L957Z3aX2WU/ZmZ3"
    "aJrMbWsEcR7uzH6lPOe3hcJXUbe3ioa9ZUe+Ne/UYN6+vb27W1DeKsKY5uGNx4EHd4owhxuHNy7n"
    "9vDw8FYZxjx8Szi3bw/NQ1XdmCXKgS3h0FS1NIXbDYK5vZ2Nb2DOEpuxsKQxpQ3AzMaISWrGWlur"
    "9SUxtyZgzLe3NwNSjhMPKfUnk9HEkt0CShtvb1rV6nq12hokUGzbtmQxtzeHGxtvW63qeqkEmHEc"
    "xrLhi22NRrYEZAYLMoDRW631daS04uaMtCBDmdEawGzhdK2vrwNlnEjp921hCrz/6gB7WUcCFvTk"
    "xP+CPUGKMGYMnNZgDN2UStBIFf+NpUwsq1azJ1DCczZYXx8MsCHgrbfwnxgKDG7V1pDS709EUYCp"
    "4uo7jjOFDc2JWfwJDm7Bv/Zo1K/h/tkXIs3o2rd++AG3gukPTjSk36/VYFh7MoLvSqXSWq1W64+4"
    "ObPWoOquPuwz48gJu4MlH8H+iJTJpLZWQswagtI4Y6xCwRlXYU1wl0RSaRy7+DA+7Plk8Uc1Wi4n"
    "iQEHrfEY9slWtTWFRy1yiIGnnPjNGMbHYwzMWb9PvhBOPxZDdnfE4Fq0nCkwkQJbtUMqDtO34eBP"
    "Mf3RiGwI0I4VByFHExcyGCOmhY2McVMbDKaRHFx523ILvic0xPSt6J1xHfdBcqhHCHYwbZEDgXOF"
    "vFbkGSCw5y96gq16FIXBPRCPJbjXw1RBjeHdD3BdnGF3UK1GY3D92cMLaQjbgaWxIilVXG3sY0CO"
    "kYPxdEoWZECOz9UqTNoSBGfLDp+jyaz1I+ZsBmvfwhMKvPcBPa/AEk3p2gzoOxhMlzD2qDay7OVr"
    "AdxNI5qZ4RY1wAlq0QmrlvCQSTcFpMPXwXRpk4Zzi2VHXXMgZmll4LQ1xs0Jx8f1JyiyYbfIF5wv"
    "oAyieok86BNM+LJjRgDkvQ8Iyp06fAZWBTlkT1qi9GsxZxayOFbouDWmk0UOMYSCGNjMYGWq7vPw"
    "7dI+Y0dOGMUgJYCZVU9bJXLqhQPLKRTZ2nCDG8N3rdbp6dSZYo1D628nnCUBE1z/2fbpdml9e3/f"
    "o5zu7+9vr+Mz++vb2/uUgj8Mrj8cwRJOxVZoymY4Jgx56oyRsr9PICUEIwswcCAYn+IPAxg4viRR"
    "JkHK1dXpPkKunCv4FjDbyPAo8PXKmcJL9vGHAcooqRdoxgqc6a+ujvb3j67gHQPmCGp7+x7U9j48"
    "Da0cHTnTfXwIL7viW3x3v2EgVzuPj2DwK8ejPIbauXcPnybfA8WBx/fg8eMrh90nk6+QApRSCca7"
    "vITtB9b48vKSYnB0fICQS8ep7yDlEr91FofKlOuwBWV2VIJ3DRDcSh2kXOKcIQP+ACxA4EfNjR3y"
    "Xhx47KRvx0EKXq5e7uzgmyQUHJOCLh/DsI8fk/0Eh3WOsCno7d49gsHfdBzeq+LL7uxyr7u316Vj"
    "7e3t3NuBR929nR382r1093hYtEt40MUFg2mbdeHnlzyU2XAPMHvdGY42pGNNAbhDMfBfdzgdDt0d"
    "3hnSZ3d2drrDIbyXIV8zs716uQuY2bDrDzXr1usEsFcn3wwXZxVnC56HZ+v4R7k87JbLHBQYsItz"
    "NnSG3nFwOBsO93B0gJTLdfh2b7g4djUawy6ODz8pl2fwu8M9DkoHXm/2oG9/oN600zFNs1M3O2a5"
    "/LBj1s0ee4R0nF6vUy9DP+asB3+aHJR2vY299Py+e712GyBm26zDn+2tzXa71wtei+Gu224DHN5d"
    "z+xxUHpmvWy2mSUECFLwK4Cg0Xq9F8ZQEjCwJa5trGNiM/5LOzA0YXTaCKqX4T3Dtx3E/BLizOA3"
    "zQ7X/uI4ptlcvFNcC2il2el0mk3zl0D1gg9hY2yafDslbX4B6WyUyhu4+GekmlCN5cKnz87u7s7O"
    "pP5nQrtZRgoCYLDd5LobTfCF4pRmo1zegN8ko1Swtra2jK3lwh/djSx4lQSnWScQOvrWI6jNTcMw"
    "NjcferVJC36CcANeKY5p1jeOj4+RQQA4uGEUDeP+oh5AkacpCjjwG0KQxm59/gQxSKGQBw+gl/s/"
    "LYqCaFePHsHcwesv50KY4/mvv/58fX3NUh5AJwkUeDWcjOb87RwfPwEIFPzm9YJyP56CL/yLFve0"
    "HR9TiAe6vk6g0Bd8+OsvQcr8ya/HPwfqOlA/BR+eX1y8/wCUT59uPn/+fPz5M9/izA8WrWD9CnVw"
    "cPDkydOnx8fPnj+/fnFy8vLly1ev3/z2+x/v3iHj48dP/7n++3//+4I152slQPEZFAIUF4KUs3Of"
    "8un6778phQszPzjAkX0EMkgjT4FBIScu5HegXLz3exGgQCsU49ZBsBEXAvPFtBKicGDmTxBz4BNc"
    "Rhjit0InDCg33rpwUZ5SzIGP8BhRENrKn24rIpSnOLJHcBluIxGQiFZ4KMdPKcdDUAbTSCSEbYWH"
    "8uwYOV4dLxiLRgKQP5cgPJTnz54dM/WMYcRBPgUhPJQXz5/jyM8ogCAWDC4ID+XkBY67ICwx8MAS"
    "vya8u+XJyYsXz/16sWAEGnH3RkkIYF7isC9onZwEGexsRS08L6QwfwVDnjDlMrxGAkvy35swhJNS"
    "mL959eplsF4FGkmYLW4IYM7evGZArxiG38ifWSGAuTj77fXrV169dhl/pDbyRegqZj6/OP/9tzev"
    "ab1BBpmsxGUHxlzwwm/+4f07ALn1+xmdrBwb8dr5+PHi3fk5ueg/dxl+IzcRDAmIy/lw8c6ri+DB"
    "MR+Gx/n04f0Fqff+bN1kX5AwZ/7x0zU5OnuQ/3qNkGcJIhvDA5HxPrjnXr8R8mwuCFrkInIeLvJs"
    "fp/Au9eqXM/q0iWnLGhPiQOjPSWZSfvqPKUMphK/p+RCpDDcnhJC1tbWJpIYTk/JNZUmo4mMqcTr"
    "KaGpZFOMOIXbU3I/kxI3lYQ8JWkfSthTwg+uxH0oMU8JTSUpH0rAU6KmkqwPxecpeaaSrA/F5Sn5"
    "plLYh+KnpHtKvqkU9KE4+hH1lGDzmoR8qFQbKsZTOrpK2PepCcX4UGnWlZSnRDA240PV+onWlZyn"
    "hHPWZ30oICVYV0mekhPvKVHpivGhULrqk7kT9ZSIrRKrQ00idKg46UrOU6IbGXN0oZJSnHQl6Smh"
    "ExHUoVwZKlq6kvSU4KBfG9m80pWspwS9RAgecdKVrKeEotKIV7qS9pRQuoo+sURIV9KeUoLgsSxd"
    "8XhKnQhPiYhK3NIVj6fUaS57SomikmWFKNKekj1JON8Dht3K5D0le5RMYRYmi6c0SnauWAqXp/Q4"
    "2lNKca58Cqen5OzsbIh6Sj5FxFPa2hX0lFyIak+JUNI9pUo2T4lSUj2lrS3WU+quxFNyHBWeUn0l"
    "nlLb/F48JaO4Ck+pWMnNU6K15Cqd3eXkKZHaNeI0pcyekmdCVSoVw/A9pUekvEdAsaQEIs9TouOT"
    "cYlAtMmISp6qZLiqkrSntMuKStALUWK8MogNQ8j4Hrby8pQC1g1aS0o8paDbY3xrnlKRlGpPiVKU"
    "e0pNo1istBV7Si5EtafUZntR5ilFUvL2lHyIWk8JtrBVeEpIUe8pFbWnpD0l7SlpT0l7StpTkuJo"
    "T0kWoj0lXSpLe0o8GO0pyUzaV+gpZcFwe0oFT1WSmDNuT4maSnLJTfyekp/cJNMMt6e0SG4Sxgh4"
    "SovkJiEfStBTkjSVhD0lN7lpJKYQiXpKBapDifpQQp4SFZXQVBL3oXg9pQJRk1xRSdiH8jylH38k"
    "ntKP8TZU3wtuktCh+DwlIir5wU2uDsWBEfaUCn5wk6dDpYZQSeQpscFNVIdKC6GS85Tc4CZfh0oJ"
    "oZL0lIh3g6KSq0N52tUkV08JKTS4ybOhYHtYi5OuZD0lL7eJSYeCrkg30RQZT8kTlUI6FHZj5ecp"
    "hXOb2AyqSIqUp7Sc2+RnUPUl8pTq0Z5SVG6TqynJeEpmO9JTis5tslAfqeWWp4SnFjvWhgonHWXw"
    "lKJPklHSlWyeErFIbF7pSjZPKSm2yVqyoWQ9pWQbKkTh9ZQ2wp5ScmxTMOiK21Mq10OeUsFKjG3K"
    "yVMqTJJtKCboKtFT2mU9peU8pZTYJj/oKsVT2trKkqfk/rVGsadEKTx5So1MnhKhcOQp7TYyeEpI"
    "0Z4S6ykZxVV4SsUKz1X395On1Om040QlEqdkFGX+zwjjKfnjJsQp7RYr2Twld3QvU4nxlAyqKqGm"
    "tJXJU2owohLRbxhRyTAMVGEM9IceZfKUAqLSgwesp0TsqIeUhJpSXp5S2CAyjBV4SvcN7Sn5n1Bp"
    "T0l7Sl+RpwQYoKj2lAhFuafkUhR7SpSi3FNCTEe5p0Qo6j0lPFquwFMqFlfhKRW1p6Q9Je0pFbSn"
    "lAWkPSVdugRkAu0pcWC0pyQzaTpPSXzOdJ6SWOk8JTGMzlPKkKeU4inpPCUJT0nnKf2jeUqdleQp"
    "1fd0nlIYovOU/qV5SsRTaqvOUyKeUrv5781Tqq8kT6nR/KbylJpJnlJueUrNZhZPacH45/OUuivJ"
    "Uwre903nKek8JcpZrafEpRFlzlPikrvYispTCpehIk9poSlRT8nPV8ozT2lZU6L5SrnlKRm+dxPI"
    "UzKMPPOUUK7iMIiyekpGukGkPSXtKWlPSXtK2lP6fjwlQlHvKXUQo9xTohTVnhKhqPaUpCFCntIS"
    "RY2nBOfKVXhKLEWdp1TUnlKIoz0lmdKekq5vo7SnxIPRnpLMpH11npK0pSTiKUmnHBUEPCU35Whi"
    "yW4BXJ6Sl3Ikh+H1lLyUI0Gzx/tMhtNTkvSHBD0lN+VI2B8S95Sk/CFBT0neH+L3lBYxR+L+EK+n"
    "RC2lsD80EVgcjvu+uZZSwB9KiQYKU9I9JddSCvpDa+kGkbintIg5cv0h3yBKYsR5Slb8ZoyW0sIf"
    "ImE6sWYPgcR7SpYVtwW4MUeeP0TUHgztqVlxEBlPyYs5WiQQudlAkWqPrKcU2PMtNhtolON930IC"
    "0SIbKErtkc1TCuUceQ1Fqz3SntJSztGCk6OnZEdHt0SqPfKeUmTOEeEsqz3ynpLdr3GrPfKekh2f"
    "dbOk9sh7Skl+RzC2pxDrKZXT8pQSgo4KIR2mEO8plVPylOzE3B42tgcr2VMqx3tKo0my2xNQrpLz"
    "lDbqsZ5SYtCR78NQSIb7vqW5PQwli6eUfGpnZCju+74Je0o+ReS+b8KeEstQ6ClRiGpPiVK0p6Q9"
    "pe8hTynSUGo08Omzs5zu+7abXJk9JSopGaykFCz0l+5GFrxK3lOioxuG4VlKm6Gbvm26kpIhpUNR"
    "T8nVlEhy0pKn9IA6NygqEQMra54SEZVSDaLMeUoGr6dkFFfhKRUr2lPSnhJXK9pT0p6S9pS0p6Q9"
    "JT7M1+YphSkqPKUlhhJPKURR4imFGWo8pQBFlafEQpR5SghpqveU4HpvFZ4SuXbN7xP4GE+pqD0l"
    "XbmV9pR4MNpTkpk0AU9JVh8S8JSsDJYSt6dEQo768jYUl6dkUUsJY2iktwAOT8mzlKT8oQKvp5TJ"
    "UuL2lOTukuZ/IsPpKZHAJil/SNRTsieCqo2HEfCUPEvJ84dEooF4PSXPUgr4QwIcHk+JsZQW/hCH"
    "2cMuTqqnxFhKjD+0Vksxe4KUNE8paCn5/lB/jZo9KfdkE/GU3JQj+MNPBnKjgWLVnoJEnpLtxhxZ"
    "o4VARM2eGLWnIJWn5MccsQFEfUxUilZ75Dwlm931ETSyvJuyRao9cp6SSwmd12LVHklPCSgRAlGs"
    "2iPpKUVoSgXfIIq4B6icp2SPalb0jb+i1B5ZT8mOvcMUVXuWDSIZTylWU4pSe2I8pWaqpxSvKUWo"
    "PTGeUt1M85QSTRVryYZK8ZSaMZ5Sot4RVntS85SazUhPKVlTQrWHy1NKue8bakqJGEvAU4rNU0oO"
    "OgpTeO/7FvaU7JGIQSTrKVmWzW0QyXtKk1RPiYEo9JTYK1btKWlPiVS6p1RZiae0u6s9pX/YU4o0"
    "lGidkUAlqb+BM54Sk5y0XIToBiqJUzxPieQo+clJ7g3fApJShcQ2WY1GBk8JR/aTkxaSkqcpESaG"
    "HBlSOhTrKblRR/GeEkEZld2M930LGkSGIk8pYBBBZ6vIUzJ0ntISRXtK2lPSnpL2lLSnxHOI0Z6S"
    "9pS0pyTH0Z6SHCjCU+rA5V5zBZ4SuXRV6inB32o7D+Fvz+o8pUqlyFalooTSC1dB1z9U2lPiwWhP"
    "SWbSOD2lTP4Qr6dkWZkx6Z4S3otNPuWowOkpWWsle2JlwnB4SsRSkveHCnyeUkZLidNTWqQc2TIE"
    "Tk+JsZQm4hQBT4n4Q/bEq4JIMhC3p4QCEWpKfRmBiNNTIq6dF3MkJRBxeEoT17QiMUdMABG/QMTh"
    "KYU0JT+AiApEFiclxVPyNSU35sgLIPKigRIx3J7SXcHXlIjSswggcqOB8vOUEOPGHDEBRJ7ZExt1"
    "JOopMfdJcwUil1OLUXukPCU7ZCharECUm6cUvlFagRWVcstTitCUKIlgrJw8JXsU4/bQiCg+T6mX"
    "5ikRTSnmOBpHWfKUzLbnKZnRnlLCOcwiao+Yp2SakZ4S3igt+cZfSxSJPCXbTqRM8slTspPFC0vQ"
    "U4rJU0qzOywxTykmTynFU1qiyHpKKT5MkCLrKY1EKPKeksV/LSbvKYlcV/J4Ss1oT0mgFR5Pqak9"
    "JQqR8pQ2V+IpbW7qPCWdp/Sv9pQ8SandwRfk4ykla0qNRg6eUvBub26yEaspYWxTdk/Ju+Wbf8M3"
    "I6ApkTClXWO3kdFTcgnUUyJu1MJT2tzESCfoyzCyekpcBlG+nlKcDaXv+6Y9Je0paU9Je0raU0rB"
    "aE9Je0raUxIt7SnJcrSnJAthBux0PE+p3VbgKYUUJUWyUi++CrpWX9pT4sFoT0lm0nSekvic6Twl"
    "sdJ5SmIYnaek85R0ntJXnKe0Rz2lK7V5Sldd4ikNuzpP6bvLUxqsJE8p/b5v+eYpna4kT0nOU5LJ"
    "U2qvJE+p2dB5Sj7lO85TKq/EUyqXdZ6S9pS0p/QN5yntriJPKaQqGUrylB4Fb/pGc488UcnILU8p"
    "4Cndv28weUqAzC1PKdbt8WKjFHhKrNuD07cCT8lYhaf04OFD+gKlnhLW+YVyT+kP/DT2g2JPiX7U"
    "r9xTOnfFCLWeEm1Fsad0Tj+/Vu0p0VZUe0ruqij2lHyIUk+J/SheoadEfRXVnlIUJH9PaXm6lHhK"
    "chBRT0kSIugp3YQhKjylJYYST0keIuIphRhKPKWlRpR4Slka8dpJ85S+ZGxkwUnylPJgeJxYTykn"
    "BuXEeUpfvpBnVd/3jVKU3/ft+noV93271vd9+xbq/5LYnps="
)

SMALL_DATA = (
    "eNrt3A1T2kgYB3B67CCjngqkRl6k1viCgNiaIY5ajzLWtnixHXsXRtZAvv+3uOfZ8JKQTdilp9Wa"
    "7QiUyd8NIR1+88+WRGL+cX9/z+5KMpmDHwO8HchkSqWPg/uDklRmefnjvXkwNQ+lNCJzkPr4wzAM"
    "x5ewLSsi0ztQtXRK1bwZmrCpHbY9DENNq6o/kkjYuh06h5Y2DDOd9kcsmodds6yQkAYzvNLUV56I"
    "peuW3dIX8vlgyjQhYqppGOYkMrBb1LKtvDv8IRP2yVA104CZTMe3Z5ZNW7qut6YyZlo1MOGYGkxi"
    "eg80vHqKA2IL+uRwm5qqaYaR1rSu4ziQVSeZ0TGmVNfzk0wP9gcOl5ZKm11Dhb9AdJRo0cl5oI8j"
    "PdMwTZhFg83hJeGD8SGw8553ZZLpNdOwkdnU8H3sqlrT7HZH09i2942k48h6ersJkeb2enp9O73e"
    "dLomHnQ3MnWSuvfXte2ac33drK0vLWGk5mxvXzcdXiThRnobtY7jdK9rb2DUOvDjbCzBDWZsixfp"
    "1TCScDqdDoRqb+B1JLbgqU4NMj3b5p3A1U61CpFyeaNcLVerHXzlDjzcqDrVjZ4TiFSrEDrB33dS"
    "KJfL8HPCNtqsFgrlwuLJYiDSKyz23F9Ur5T2S/uLuf26u5HjVPYL9V4hOEu94CYqsD2MQqlQr4+2"
    "cpweLwLPsydLi6VSpd1+y8YmDLxvD9pO6D/7/c3FdrtdVBQlR3JF/INDGcCTYZGt5UZbyWUzmTVC"
    "yBqMFfYwS4gSltns79zmILIG2638iWNldXUtk8nmbhudPi/RaOy8fn0LY21tdWUSwWf+htHgRPqQ"
    "YOPWN64+f7n59s+/d3fBefq7bmRnd3fv8PDo6N3x8enZh/anq883327DIrs7O7D97t7eYePoHUuc"
    "X7Q/wSQ33zESzPT3dtn2EIDE+1Hi6gvs1w9McCKH7sAAJE6HCXwlbL94kaMGG0fuFMEEJ3L8/h2O"
    "98PAh78u3b0aJe44B/n0+Bg2ZwGc4hJe+VdPgvdmts/PTnGc4RRsp74Oj1VYAua5vDg/Oz9ngamd"
    "CklA5ubq8qLdvrwUm2IUuvn86QpeBU4xDvSjP5P7fTjSX4bn1V2j0Z8VwAHnYn844GHieY7nJ6Vo"
    "KvGkhFSKyPCkBBG7ZUlKKYJKfCkBlSzdDoMST0pIJUjoPF/xpYRUspBKqVRAV+FSsjHS0vP5BXEp"
    "WYxKegtjVpiUDJ+ULPY5znSV1xMCUpoAFqEkJCXQ1fhdwYkEpORHTCtcSpWJlKwpXFEBKfnOliHI"
    "5KREQ6TkbLwJkRLlSKkcLSXKkVLBlZIjLqXST0uJiErpLUIJfkSkBDgiJAcjW8TbgYCUskAjsgpO"
    "WlkhElJy2QPJeaSUTGYkpXRBkoqklCCyLysljEhKKZmMpRRLKZbSg0spkkpcKSXogiUpJUYlKicl"
    "6v1QFpISUEkPL6JQSn9o6h/+sie0iAqREnwi54E9ej6li0sJSyXLLaIsQSnh5zjrofS8qJSQlqyI"
    "YroSk1LLpRKDUriUSlwpQSgvKCWbV0NFdkryUvK7RxeQEm0lgriaklLOldKoU+oFcRXslKrRUqKc"
    "Tqn8s1Iic3RKiqiU3Ls2bxK/lDZBSkqxyKREssXioJVTIqVUVHI5gE4mk1lbwWqJkAxIS0BKI/Yg"
    "sl62lIgiLSWiyEuJKNJSSialpfQ9llIspbhT+vWdUkBKz7xTqqi/U6fUfYqd0pZPSiKdUlW+Uyr/"
    "gk6pN1enRGZ2SkrO7ZSwWxLplEgWoMQ6JbwIJ9Ip4bW6sZRWYyk9VSkRRVpKRJGV0i1RpKWUjKUU"
    "S0lWSvE6pYdZp0QfZZ2S8XusU0rNt05p+bHWKTmPtE7paUpJZp0SASgVpdYpsTVKwB2ZdUoQ8S46"
    "cqVEYinFUhKSEiGSUholJKRESEVWSkSRllIyltJ8UqKyUqLRUOJJaQaUeFKKuI4WLiU7oh7iSolB"
    "idVDlqCUGJRYPRRQT4iUho0Suyq2sCC6ohsvpA37oQVP2RMlpXE/5Ct7IqU0wSj1lD3RUvL6tcWT"
    "khqUEuca1ywpJWZIiXVKWxMpTRtGYEV34AybLSVq8U7KZyel4gNKySXS6OrbbCnhIiWGJPd2szho"
    "RUsp55VSZiSl4iwpuewhRHpFN4mlFEvpaUqpQrYeWkr14VBeuJSi0cOT0iwocaQUcR0tTEo0qh4K"
    "kxJeRwvth3hSYiuO3OVD/FhASpaFUMJGSVRKA5tdR0MpsatiVEhKQygxv3jLnggp2aMjJi4l26K8"
    "y2JeKdVRSupESn5dUJFOyVcpedkTLiU7pCCKuPrGb3vkpJSYLSV+4n+U0pK8lDJP8erbaJ3S7E7J"
    "vfCWJYglXLE0W0psjdLqKoIJHuHybuCW2DqlOaQUd0qxlF6olJS6d8SdUtwpvZRO6XrqWwIepFMy"
    "Hq9Tas7TKW3GnZLzlDolxW2TiHinhN8SgJ2SKyUi1CllvOzBVeCyUiLxtwTE//ctXqf0k+M/re24"
    "9w=="
)
