"""Packs the mascot frames into src/chaos_agents/mascot_data.py so the CLI
can render them with the standard library only (zlib + base64), no Pillow.

Two sizes: FULL is 1 sprite pixel per half-block cell (the real art), SMALL
is a 2x reduction used only when the terminal can't fit FULL."""

import base64
import sys
import zlib
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_mascot as bm  # noqa: E402

DEFAULT_OUT = bm.HERE.parent.parent / "src" / "chaos_agents" / "mascot_data.py"

COLORS = 96
FRAME_MS = 140


def content_bbox(frames):
    bg = bm.backdrop().convert("RGB")
    bpx = bg.load()
    xs, ys = [], []
    for f in frames:
        px = f.convert("RGB").load()
        for x in range(bm.W):
            for y in range(bm.H):
                if sum(abs(a - b) for a, b in zip(px[x, y], bpx[x, y])) > 24:
                    xs.append(x)
                    ys.append(y)
    pad = 2
    return max(0, min(xs) - pad), max(0, min(ys) - pad), min(bm.W, max(xs) + pad + 1), min(bm.H, max(ys) + pad + 1)


def even(n):
    return n + (n % 2)


def encode(indexed, w, h, n):
    idx = indexed.load()
    raw = bytearray()
    for i in range(n):
        for y in range(h):
            for x in range(w):
                raw.append(idx[i * w + x, y])
    blob = base64.b64encode(zlib.compress(bytes(raw), 9)).decode()
    return [blob[i: i + 76] for i in range(0, len(blob), 76)]


def main(out_path):
    n = len(bm.FRAMES)
    frames = [Image.open(bm.OUT / f"frame_{i}.png").convert("RGB") for i in range(n)]
    box = content_bbox(frames)
    full = [f.crop(box) for f in frames]
    fw, fh = full[0].size
    fh2 = even(fh)
    full = [f.crop((0, 0, fw, fh2)) if fh2 == fh else f.resize((fw, fh2), Image.NEAREST) for f in full]
    sw, sh = fw // 2, even(fh // 2)
    small = [f.resize((sw, sh), Image.LANCZOS) for f in full]

    # one shared palette across both sizes and every frame
    strip = Image.new("RGB", (fw * n + sw * n, max(fh2, sh)))
    for i, f in enumerate(full):
        strip.paste(f, (i * fw, 0))
    for i, f in enumerate(small):
        strip.paste(f, (fw * n + i * sw, 0))
    # median-cut drops rare colours, and the eyes are only a few pixels --
    # reserve exact slots for the colours the animation depends on.
    keep = [bm.EYE, bm.EYE_HOT, bm.BREW, bm.BREW_PALE]
    base = strip.quantize(colors=COLORS - len(keep), method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    flat = base.getpalette()[: (COLORS - len(keep)) * 3] + [c for rgb in keep for c in rgb]
    pimg = Image.new("P", (1, 1))
    pimg.putpalette(flat + [0] * (768 - len(flat)))
    q = strip.quantize(palette=pimg, dither=Image.Dither.NONE)
    palette = ["#%02x%02x%02x" % tuple(flat[i * 3: i * 3 + 3]) for i in range(COLORS)]

    full_q = q.crop((0, 0, fw * n, fh2))
    small_q = q.crop((fw * n, 0, fw * n + sw * n, sh))
    full_lines = encode(full_q, fw, fh2, n)
    small_lines = encode(small_q, sw, sh, n)

    def block(name, lines):
        return f"{name} = (\n" + "".join(f'    "{l}"\n' for l in lines) + ")\n"

    with open(out_path, "w") as out:
        out.write('"""Generated by tools/mascot/export_terminal.py -- do not edit by hand.\n\n')
        out.write('Nergal, the chaos-bringer mascot. Demon sprite by Stephen "Redshrike"\n')
        out.write('Challener (with Blarumyrran and LordNeo), from "6 More RPG Enemies" on\n')
        out.write("OpenGameArt.org, CC-BY 3.0 / OGA-BY 3.0; recolored, re-posed and composited\n")
        out.write('with an original cauldron for chaos-bringer. See CREDITS.md.\n"""\n\n')
        out.write(f"FRAMES = {n}\nFRAME_MS = {FRAME_MS}\n\n")
        out.write(f"FULL_WIDTH = {fw}\nFULL_HEIGHT = {fh2}\nSMALL_WIDTH = {sw}\nSMALL_HEIGHT = {sh}\n\n")
        out.write("PALETTE = (\n")
        for i in range(0, COLORS, 8):
            out.write("    " + ", ".join(f'"{c}"' for c in palette[i: i + 8]) + ",\n")
        out.write(")\n\n")
        out.write(block("FULL_DATA", full_lines) + "\n")
        out.write(block("SMALL_DATA", small_lines))
    print(f"wrote {out_path}: full {fw}x{fh2}, small {sw}x{sh}, {n} frames, "
          f"{sum(map(len, full_lines)) + sum(map(len, small_lines))} base64 chars")


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUT)
